title: GameDevone Projects
description: Flavorful Project Blog
show_downloads: true


baseurl: "/GameDevone" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://gamedev-one.github.io" # change this to the base hostname & protocol for your site

google_analytics:
theme: jekyll-theme-leap-day